## Pandas Continued

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("C:/Users/goyal/OneDrive/Desktop/Kaggle_Groupby.csv")

In [ ]:
df

Unnamed: 0  Season  Episode  Rating       Code            Title
0               0       1        1     9.4  tt5491994  Planet Earth II
1               1       1        2     9.1  tt5491994  Planet Earth II
2               2       1        3     8.9  tt5491994  Planet Earth II
3               3       1        4     8.8  tt5491994  Planet Earth II
4               4       1        5     8.6  tt5491994  Planet Earth II
...           ...     ...      ...     ...        ...              ...
15113         176       6       23     8.2  tt0043208      I Love Lucy
15114         177       6       24     8.8  tt0043208      I Love Lucy
15115         178       6       25     8.4  tt0043208      I Love Lucy
15116         179       6       26     8.5  tt0043208      I Love Lucy
15117         180       6       27     7.9  tt0043208      I Love Lucy

[15118 rows x 6 columns]

In [ ]:
df.columns

Index(['Unnamed: 0', 'Season', 'Episode', 'Rating', 'Code', 'Title'], dtype='object')

In [ ]:
df = df.drop('Unnamed: 0',axis =1)
df

Season  Episode  Rating       Code            Title
0           1        1     9.4  tt5491994  Planet Earth II
1           1        2     9.1  tt5491994  Planet Earth II
2           1        3     8.9  tt5491994  Planet Earth II
3           1        4     8.8  tt5491994  Planet Earth II
4           1        5     8.6  tt5491994  Planet Earth II
...       ...      ...     ...        ...              ...
15113       6       23     8.2  tt0043208      I Love Lucy
15114       6       24     8.8  tt0043208      I Love Lucy
15115       6       25     8.4  tt0043208      I Love Lucy
15116       6       26     8.5  tt0043208      I Love Lucy
15117       6       27     7.9  tt0043208      I Love Lucy

[15118 rows x 5 columns]

In [ ]:
df['Title'].unique()

array(['Planet Earth II', 'Breaking Bad', 'Planet Earth',
       'Band of Brothers', 'Chernobyl', 'The Wire', 'Blue Planet II',
       'Avatar: The Last Airbender', 'Cosmos: A Spacetime Odyssey',
       'The Sopranos', 'Our Planet', 'Cosmos', 'Game of Thrones',
       'Rick and Morty', 'The World at War',
       'Fullmetal Alchemist: Brotherhood', 'The Last Dance', 'Life',
       'Sherlock', 'The Twilight Zone', 'The Vietnam War',
       'Batman: The Animated Series',
       'Scam 1992: The Harshad Mehta Story', 'Arcane', 'The Blue Planet',
       'Attack on Titan', 'The Office', 'Firefly', 'Human Planet',
       'Frozen Planet', 'Death Note', 'Only Fools and Horses',
       'True Detective', 'The Civil War', 'Hunter x Hunter',
       'The Beatles: Get Back', 'Seinfeld', 'Persona', 'Fargo', 'Dekalog',
       "Clarkson's Farm", 'Cowboy Bebop', 'Better Call Saul',
       'Nathan for You', 'Gravity Falls', 'Friends', 'When They See Us',
       'Last Week Tonight with John Oliver', 'Africa

### Groupby

In [ ]:
df.groupby('Title').get_group('Breaking Bad')

Season  Episode  Rating       Code         Title
6        1        1     9.0  tt0903747  Breaking Bad
7        1        2     8.6  tt0903747  Breaking Bad
8        1        3     8.7  tt0903747  Breaking Bad
9        1        4     8.2  tt0903747  Breaking Bad
10       1        5     8.3  tt0903747  Breaking Bad
..     ...      ...     ...        ...           ...
63       5       12     9.1  tt0903747  Breaking Bad
64       5       13     9.8  tt0903747  Breaking Bad
65       5       14    10.0  tt0903747  Breaking Bad
66       5       15     9.6  tt0903747  Breaking Bad
67       5       16     9.9  tt0903747  Breaking Bad

[62 rows x 5 columns]

In [ ]:
df.groupby('Title').get_group('Breaking Bad')[['Rating','Episode','Title']].mean()

C:\Users\goyal\AppData\Local\Temp\ipykernel_12592\66619443.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.groupby('Title').get_group('Breaking Bad')[['Rating','Episode','Title']].mean()


Rating     8.956452
Episode    7.048387
dtype: float64

## Query Method

In [ ]:
df.query('Title == "Breaking Bad" and Rating == 9 and Episode == 6')

Season  Episode  Rating       Code         Title
57       5        6     9.0  tt0903747  Breaking Bad

In [ ]:
df.query('Title == "Breaking Bad" ')

Season  Episode  Rating       Code         Title
6        1        1     9.0  tt0903747  Breaking Bad
7        1        2     8.6  tt0903747  Breaking Bad
8        1        3     8.7  tt0903747  Breaking Bad
9        1        4     8.2  tt0903747  Breaking Bad
10       1        5     8.3  tt0903747  Breaking Bad
..     ...      ...     ...        ...           ...
63       5       12     9.1  tt0903747  Breaking Bad
64       5       13     9.8  tt0903747  Breaking Bad
65       5       14    10.0  tt0903747  Breaking Bad
66       5       15     9.6  tt0903747  Breaking Bad
67       5       16     9.9  tt0903747  Breaking Bad

[62 rows x 5 columns]

In [ ]:
df.query('Title == "Rick and Morty" and 8.5 < Rating < 9.5')

Season  Episode  Rating       Code           Title
418       1        2     8.7  tt2861424  Rick and Morty
420       1        4     8.7  tt2861424  Rick and Morty
421       1        5     9.0  tt2861424  Rick and Morty
422       1        6     9.0  tt2861424  Rick and Morty
424       1        8     8.7  tt2861424  Rick and Morty
426       1       10     9.3  tt2861424  Rick and Morty
428       2        1     8.8  tt2861424  Rick and Morty
429       2        2     8.8  tt2861424  Rick and Morty
433       2        6     9.3  tt2861424  Rick and Morty
437       2       10     9.3  tt2861424  Rick and Morty
440       3        3     9.3  tt2861424  Rick and Morty
443       3        6     8.9  tt2861424  Rick and Morty
445       3        8     8.9  tt2861424  Rick and Morty
448       4        1     8.9  tt2861424  Rick and Morty
452       4        5     8.8  tt2861424  Rick and Morty
455       4        8     9.4  tt2861424  Rick and Morty
457       4       10     9.1  tt2861424  Rick and Morty
458       5        1     9.0  tt2861424  Rick and Morty
459       5        2     8.7  tt2861424  Rick and Morty
467       5       10     9.4  tt2861424  Rick and Morty
468       6        1     9.0  tt2861424  Rick and Morty

In [ ]:
df.query('Title == "Rick and Morty" and 8.5 < Rating < 9.5').sort_values('Rating',ascending = False).nlargest(10,'Rating')

Season  Episode  Rating       Code           Title
467       5       10     9.4  tt2861424  Rick and Morty
455       4        8     9.4  tt2861424  Rick and Morty
440       3        3     9.3  tt2861424  Rick and Morty
433       2        6     9.3  tt2861424  Rick and Morty
426       1       10     9.3  tt2861424  Rick and Morty
437       2       10     9.3  tt2861424  Rick and Morty
457       4       10     9.1  tt2861424  Rick and Morty
458       5        1     9.0  tt2861424  Rick and Morty
468       6        1     9.0  tt2861424  Rick and Morty
422       1        6     9.0  tt2861424  Rick and Morty

In [ ]:
df.query('Title == "Rick and Morty" and 8.5 < Rating < 9.5').sort_values('Rating',ascending = False).nsmallest(10,'Rating')

Season  Episode  Rating       Code           Title
420       1        4     8.7  tt2861424  Rick and Morty
424       1        8     8.7  tt2861424  Rick and Morty
459       5        2     8.7  tt2861424  Rick and Morty
418       1        2     8.7  tt2861424  Rick and Morty
429       2        2     8.8  tt2861424  Rick and Morty
452       4        5     8.8  tt2861424  Rick and Morty
428       2        1     8.8  tt2861424  Rick and Morty
443       3        6     8.9  tt2861424  Rick and Morty
445       3        8     8.9  tt2861424  Rick and Morty
448       4        1     8.9  tt2861424  Rick and Morty

In [ ]:
df.groupby('Title').get_group('Rick and Morty')['Rating'].min()

5.7

## iloc Method

In [ ]:
df.iloc[0:3]

Season  Episode  Rating       Code            Title
0       1        1     9.4  tt5491994  Planet Earth II
1       1        2     9.1  tt5491994  Planet Earth II
2       1        3     8.9  tt5491994  Planet Earth II

In [ ]:
df.iloc[0:3,1:3]

Episode  Rating
0        1     9.4
1        2     9.1
2        3     8.9

In [ ]:
df.iloc[:,-1:]

Title
0      Planet Earth II
1      Planet Earth II
2      Planet Earth II
3      Planet Earth II
4      Planet Earth II
...                ...
15113      I Love Lucy
15114      I Love Lucy
15115      I Love Lucy
15116      I Love Lucy
15117      I Love Lucy

[15118 rows x 1 columns]

In [ ]:
df.iloc[[0,1,13,15,18]]

Season  Episode  Rating       Code            Title
0        1        1     9.4  tt5491994  Planet Earth II
1        1        2     9.1  tt5491994  Planet Earth II
13       2        1     8.6  tt0903747     Breaking Bad
15       2        3     8.3  tt0903747     Breaking Bad
18       2        6     8.8  tt0903747     Breaking Bad

In [ ]:
df.iloc[[0,2,13,14,15], [1,3,4]]

Episode       Code            Title
0         1  tt5491994  Planet Earth II
2         3  tt5491994  Planet Earth II
13        1  tt0903747     Breaking Bad
14        2  tt0903747     Breaking Bad
15        3  tt0903747     Breaking Bad

## loc Method

In [ ]:
df.loc[df['Rating'] > 9.5]

Season  Episode  Rating       Code                 Title
32          3        7     9.6  tt0903747          Breaking Bad
38          3       13     9.6  tt0903747          Breaking Bad
48          4       10     9.6  tt0903747          Breaking Bad
49          4       11     9.7  tt0903747          Breaking Bad
51          4       13     9.9  tt0903747          Breaking Bad
...       ...      ...     ...        ...                   ...
14807       4       50     9.7  tt0988818               Gintama
14808       4       51     9.6  tt0988818               Gintama
14818       5       10     9.6  tt0988818               Gintama
14852       8        7     9.7  tt0988818               Gintama
14929       1       18     9.8  tt1298820  Clannad: After Story

[197 rows x 5 columns]

In [ ]:
df.loc[7:9]

Season  Episode  Rating       Code         Title
7       1        2     8.6  tt0903747  Breaking Bad
8       1        3     8.7  tt0903747  Breaking Bad
9       1        4     8.2  tt0903747  Breaking Bad

In [ ]:
df.iloc[7:9]

Season  Episode  Rating       Code         Title
7       1        2     8.6  tt0903747  Breaking Bad
8       1        3     8.7  tt0903747  Breaking Bad

In [ ]:
df.loc[7:9]

Season  Episode  Rating       Code         Title
7       1        2     8.6  tt0903747  Breaking Bad
8       1        3     8.7  tt0903747  Breaking Bad
9       1        4     8.2  tt0903747  Breaking Bad

In [ ]:
df1 = df.query('Title == "Rick and Morty" and 8.5 < Rating < 9.5')
df1.set_index('Code')

Season  Episode  Rating           Title
Code                                              
tt2861424       1        2     8.7  Rick and Morty
tt2861424       1        4     8.7  Rick and Morty
tt2861424       1        5     9.0  Rick and Morty
tt2861424       1        6     9.0  Rick and Morty
tt2861424       1        8     8.7  Rick and Morty
tt2861424       1       10     9.3  Rick and Morty
tt2861424       2        1     8.8  Rick and Morty
tt2861424       2        2     8.8  Rick and Morty
tt2861424       2        6     9.3  Rick and Morty
tt2861424       2       10     9.3  Rick and Morty
tt2861424       3        3     9.3  Rick and Morty
tt2861424       3        6     8.9  Rick and Morty
tt2861424       3        8     8.9  Rick and Morty
tt2861424       4        1     8.9  Rick and Morty
tt2861424       4        5     8.8  Rick and Morty
tt2861424       4        8     9.4  Rick and Morty
tt2861424       4       10     9.1  Rick and Morty
tt2861424       5        1     9.0  Rick and Morty
tt2861424       5        2     8.7  Rick and Morty
tt2861424       5       10     9.4  Rick and Morty
tt2861424       6        1     9.0  Rick and Morty

In [ ]:
df1

Season  Episode  Rating       Code           Title
418       1        2     8.7  tt2861424  Rick and Morty
420       1        4     8.7  tt2861424  Rick and Morty
421       1        5     9.0  tt2861424  Rick and Morty
422       1        6     9.0  tt2861424  Rick and Morty
424       1        8     8.7  tt2861424  Rick and Morty
426       1       10     9.3  tt2861424  Rick and Morty
428       2        1     8.8  tt2861424  Rick and Morty
429       2        2     8.8  tt2861424  Rick and Morty
433       2        6     9.3  tt2861424  Rick and Morty
437       2       10     9.3  tt2861424  Rick and Morty
440       3        3     9.3  tt2861424  Rick and Morty
443       3        6     8.9  tt2861424  Rick and Morty
445       3        8     8.9  tt2861424  Rick and Morty
448       4        1     8.9  tt2861424  Rick and Morty
452       4        5     8.8  tt2861424  Rick and Morty
455       4        8     9.4  tt2861424  Rick and Morty
457       4       10     9.1  tt2861424  Rick and Morty
458       5        1     9.0  tt2861424  Rick and Morty
459       5        2     8.7  tt2861424  Rick and Morty
467       5       10     9.4  tt2861424  Rick and Morty
468       6        1     9.0  tt2861424  Rick and Morty

## Merge

In [ ]:
# Case 1 :Merging with one condition
data1 = {'key':['K0','K1','K2','K3'],'Name':['Jai','Princi','Gaurav','Anuj'],'Age':[27,24,22,32]}
data2= {'key':['K0','K1','K2','K3'],'Address':['Nagpur','Kanpur','Allahabad','Kannauj'],
        'Qualification':['Btech','BA','BCom','B.hons']}

In [ ]:
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)

In [ ]:
df

key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

In [ ]:
df1

key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur            BA
2  K2  Allahabad          BCom
3  K3    Kannauj        B.hons

In [ ]:
pd.merge(df,df1,on = 'key')

key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur            BA
2  K2  Gaurav   22  Allahabad          BCom
3  K3    Anuj   32    Kannauj        B.hons

In [ ]:
# Case 2 : Memrging with multiple condition
data1 = {'key':['K0','K1','K2','K3'],
         'key1':['K0','K1','K0','K1'],'Name':['Jai','Princi','Gaurav','Anuj'],'Age':[27,24,22,32]}
data2= {'key':['K0','K1','K2','K3'],
        'key1':['K0','K0','K0','K0'],'Address':['Nagpur','Kanpur','Allahabad','Kannauj'],
        'Qualification':['Btech','BA','BCom','B.hons']}
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
df

key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

In [ ]:
df1

key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur            BA
2  K2   K0  Allahabad          BCom
3  K3   K0    Kannauj        B.hons

In [ ]:
pd.merge(df,df1,on = ['key','key1'])

key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          BCom

In [ ]:
# Case 3 :left
data1 = {'key':['K0','K1','K2','K3'],
         'key1':['K0','K1','K0','K1'],'Name':['Jai','Princi','Gaurav','Anuj'],'Age':[27,24,22,32]}
data2= {'key':['K0','K1','K2','K3'],
        'key1':['K0','K0','K0','K0'],'Address':['Nagpur','Kanpur','Allahabad','Kannauj'],
        'Qualification':['Btech','BA','BCom','B.hons']}
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
df

key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

In [ ]:
df1

key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur            BA
2  K2   K0  Allahabad          BCom
3  K3   K0    Kannauj        B.hons

In [ ]:
pd.merge(df,df1,how = 'left',on = ['key','key1'])

key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          BCom
3  K3   K1    Anuj   32        NaN           NaN

In [ ]:
pd.merge(df,df1,how = 'right',on = ['key','key1'])

key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur            BA
2  K2   K0  Gaurav  22.0  Allahabad          BCom
3  K3   K0     NaN   NaN    Kannauj        B.hons

In [ ]:
df1

key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur            BA
2  K2   K0  Allahabad          BCom
3  K3   K0    Kannauj        B.hons

In [ ]:
pd.merge(df,df1,how = 'outer',on = ['key','key1'])

key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K1  Princi  24.0        NaN           NaN
2  K2   K0  Gaurav  22.0  Allahabad          BCom
3  K3   K1    Anuj  32.0        NaN           NaN
4  K1   K0     NaN   NaN     Kanpur            BA
5  K3   K0     NaN   NaN    Kannauj        B.hons

In [ ]:
pd.merge(df,df1,how = 'inner',on = ['key','key1'])

key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          BCom

In [ ]:
pd.merge(df,df1,how = 'left',on = ['key'])[['Age','Qualification']]

Age Qualification
0   27         Btech
1   24            BA
2   22          BCom
3   32        B.hons

## Concatenate

In [ ]:
df

key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

In [ ]:
df1

key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur            BA
2  K2   K0  Allahabad          BCom
3  K3   K0    Kannauj        B.hons

In [ ]:
pd.concat([df,df1],axis = 1) #Column wise

key key1    Name  Age key key1    Address Qualification
0  K0   K0     Jai   27  K0   K0     Nagpur         Btech
1  K1   K1  Princi   24  K1   K0     Kanpur            BA
2  K2   K0  Gaurav   22  K2   K0  Allahabad          BCom
3  K3   K1    Anuj   32  K3   K0    Kannauj        B.hons

In [ ]:
pd.concat([df,df1],axis = 0) #Row Wise

key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0        NaN           NaN
1  K1   K1  Princi  24.0        NaN           NaN
2  K2   K0  Gaurav  22.0        NaN           NaN
3  K3   K1    Anuj  32.0        NaN           NaN
0  K0   K0     NaN   NaN     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur            BA
2  K2   K0     NaN   NaN  Allahabad          BCom
3  K3   K0     NaN   NaN    Kannauj        B.hons

In [ ]:
df

key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

In [ ]:
df1

key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur            BA
2  K2   K0  Allahabad          BCom
3  K3   K0    Kannauj        B.hons

In [ ]:
pd.concat([df,df1],axis = 1, join = 'inner')

key key1    Name  Age key key1    Address Qualification
0  K0   K0     Jai   27  K0   K0     Nagpur         Btech
1  K1   K1  Princi   24  K1   K0     Kanpur            BA
2  K2   K0  Gaurav   22  K2   K0  Allahabad          BCom
3  K3   K1    Anuj   32  K3   K0    Kannauj        B.hons

In [ ]:
pd.concat([df,df1],axis = 1, join = 'outer')

key key1    Name  Age key key1    Address Qualification
0  K0   K0     Jai   27  K0   K0     Nagpur         Btech
1  K1   K1  Princi   24  K1   K0     Kanpur            BA
2  K2   K0  Gaurav   22  K2   K0  Allahabad          BCom
3  K3   K1    Anuj   32  K3   K0    Kannauj        B.hons

In [ ]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
               columns=['letter', 'number'])

df1

letter  number
0      a       1
1      b       2

In [ ]:
df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                   columns=['letter', 'number', 'animal'])

df3

letter  number animal
0      c       3    cat
1      d       4    dog

In [ ]:
pd.concat([df1, df3], join="inner")

letter  number
0      a       1
1      b       2
0      c       3
1      d       4

## Where pandas

In [ ]:
import pandas as pd
df = pd.read_csv("C:/Users/goyal/OneDrive/Desktop/nba.csv")

In [ ]:
df = df.drop(457,axis = 0)

In [ ]:
df.isna().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [ ]:
df.sort_values('Team',inplace = True)

In [ ]:
df

Name                Team  Number Position   Age Height  \
317   Lamar Patterson       Atlanta Hawks    13.0       SG  24.0    6-5   
309     Kent Bazemore       Atlanta Hawks    24.0       SF  26.0    6-5   
310  Tim Hardaway Jr.       Atlanta Hawks    10.0       SG  24.0    6-6   
311      Kirk Hinrich       Atlanta Hawks    12.0       SG  35.0    6-4   
312        Al Horford       Atlanta Hawks    15.0        C  30.0   6-10   
..                ...                 ...     ...      ...   ...    ...   
371      Jarell Eddie  Washington Wizards     8.0       SG  24.0    6-7   
369      Bradley Beal  Washington Wizards     3.0       SG  22.0    6-5   
368     Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   
382         John Wall  Washington Wizards     2.0       PG  25.0    6-4   
370      Jared Dudley  Washington Wizards     1.0       SF  30.0    6-7   

     Weight         College      Salary  
317   225.0      Pittsburgh    525093.0  
309   201.0    Old Dominion   2000000.0  
310   205.0        Michigan   1304520.0  
311   190.0          Kansas   2854940.0  
312   245.0         Florida  12000000.0  
..      ...             ...         ...  
371   218.0   Virginia Tech    561716.0  
369   207.0         Florida   5694674.0  
368   220.0  Michigan State   4000000.0  
382   195.0        Kentucky  15851950.0  
370   225.0  Boston College   4375000.0  

[457 rows x 9 columns]

In [ ]:
filtered = df['Team'] == "Atlanta Hawks"

In [ ]:
filtered

317     True
309     True
310     True
311     True
312     True
       ...  
371    False
369    False
368    False
382    False
370    False
Name: Team, Length: 457, dtype: bool

In [ ]:
df.where(filtered)

df

Name                Team  Number Position   Age Height  \
317   Lamar Patterson       Atlanta Hawks    13.0       SG  24.0    6-5   
309     Kent Bazemore       Atlanta Hawks    24.0       SF  26.0    6-5   
310  Tim Hardaway Jr.       Atlanta Hawks    10.0       SG  24.0    6-6   
311      Kirk Hinrich       Atlanta Hawks    12.0       SG  35.0    6-4   
312        Al Horford       Atlanta Hawks    15.0        C  30.0   6-10   
..                ...                 ...     ...      ...   ...    ...   
371      Jarell Eddie  Washington Wizards     8.0       SG  24.0    6-7   
369      Bradley Beal  Washington Wizards     3.0       SG  22.0    6-5   
368     Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   
382         John Wall  Washington Wizards     2.0       PG  25.0    6-4   
370      Jared Dudley  Washington Wizards     1.0       SF  30.0    6-7   

     Weight         College      Salary  
317   225.0      Pittsburgh    525093.0  
309   201.0    Old Dominion   2000000.0  
310   205.0        Michigan   1304520.0  
311   190.0          Kansas   2854940.0  
312   245.0         Florida  12000000.0  
..      ...             ...         ...  
371   218.0   Virginia Tech    561716.0  
369   207.0         Florida   5694674.0  
368   220.0  Michigan State   4000000.0  
382   195.0        Kentucky  15851950.0  
370   225.0  Boston College   4375000.0  

[457 rows x 9 columns]

In [ ]:
df.where(df["Team"]=="Atlanata Hawks")

Name Team  Number Position  Age Height  Weight College  Salary
317  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
309  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
310  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
311  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
312  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
..   ...  ...     ...      ...  ...    ...     ...     ...     ...
371  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
369  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
368  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
382  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN
370  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN

[457 rows x 9 columns]

In [ ]:
df
filter1 = df['Team'] == 'Atlanta Hawks'
filter2 = df['Age'] > 24

In [ ]:
filter1

317     True
309     True
310     True
311     True
312     True
       ...  
371    False
369    False
368    False
382    False
370    False
Name: Team, Length: 457, dtype: bool

In [ ]:
filter2

317    False
309     True
310    False
311     True
312     True
       ...  
371    False
369    False
368     True
382     True
370     True
Name: Age, Length: 457, dtype: bool

In [ ]:
df.where(filter1 & filter2).dropna()

Name           Team  Number Position   Age Height  Weight  \
309   Kent Bazemore  Atlanta Hawks    24.0       SF  26.0    6-5   201.0   
311    Kirk Hinrich  Atlanta Hawks    12.0       SG  35.0    6-4   190.0   
312      Al Horford  Atlanta Hawks    15.0        C  30.0   6-10   245.0   
313  Kris Humphries  Atlanta Hawks    43.0       PF  31.0    6-9   235.0   
314     Kyle Korver  Atlanta Hawks    26.0       SG  35.0    6-7   212.0   
315    Paul Millsap  Atlanta Hawks     4.0       PF  31.0    6-8   246.0   
319      Mike Scott  Atlanta Hawks    32.0       PF  27.0    6-8   237.0   
323     Jeff Teague  Atlanta Hawks     0.0       PG  27.0    6-2   186.0   

            College      Salary  
309    Old Dominion   2000000.0  
311          Kansas   2854940.0  
312         Florida  12000000.0  
313       Minnesota   1000000.0  
314       Creighton   5746479.0  
315  Louisiana Tech  18671659.0  
319        Virginia   3333333.0  
323     Wake Forest   8000000.0

# Numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.__version__

'1.21.5'

In [ ]:
arr = np.array(42)
print(arr)
print(arr.ndim)

42
0


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
arr = np.array([1,2,3,4],ndmin = 5)

print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [ ]:
print(arr[3])

4


In [ ]:
arr[2] + arr[4]

8

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [ ]:
print(arr[1,3])

9


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
9


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0,-3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3
